import type { ComplexityRelation } from './complexityTypes';

export const complexityRelations: ComplexityRelation[] = [
  { id: 'p-subset-np', source: 'P', target: 'NP', label: 'P ⊆ NP', kind: 'inclusion', truthStatus: 'theorem', layer: 'basic' },
  { id: 'p-subset-conp', source: 'P', target: 'co-NP', label: 'P ⊆ co-NP', kind: 'inclusion', truthStatus: 'theorem', layer: 'basic' },
  { id: 'npc-subset-np', source: 'NP-Complete', target: 'NP', label: 'NP-Complete ⊆ NP', kind: 'inclusion', truthStatus: 'definition', layer: 'basic' },
  { id: 'npc-subset-nphard', source: 'NP-Complete', target: 'NP-Hard', label: 'NP-Complete ⊆ NP-Hard', kind: 'inclusion', truthStatus: 'definition', layer: 'basic' },
  { id: 'np-subset-pspace', source: 'NP', target: 'PSPACE', label: 'NP ⊆ PSPACE', kind: 'inclusion', truthStatus: 'theorem', layer: 'basic' },
  { id: 'conp-subset-pspace', source: 'co-NP', target: 'PSPACE', label: 'co-NP ⊆ PSPACE', kind: 'inclusion', truthStatus: 'theorem', layer: 'basic' },
  { id: 'pspace-subset-exp', source: 'PSPACE', target: 'EXP', label: 'PSPACE ⊆ EXPTIME', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'np-conp-open', source: 'NP', target: 'co-NP', label: 'NP ?= co-NP', kind: 'duality', truthStatus: 'open', layer: 'basic' },
  { id: 'p-vs-np-open', source: 'P', target: 'NP-Complete', label: 'P vs NP abierto', kind: 'duality', truthStatus: 'open', layer: 'basic' },
  { id: 'rp-subset-bpp', source: 'RP', target: 'BPP', label: 'RP ⊆ BPP', kind: 'inclusion', truthStatus: 'theorem', layer: 'randomized' },
  { id: 'zpp-subset-rp', source: 'ZPP', target: 'RP', label: 'ZPP ⊆ RP', kind: 'inclusion', truthStatus: 'theorem', layer: 'randomized' },
  { id: 'bpp-in-pspace', source: 'BPP', target: 'PSPACE', label: 'BPP ⊆ PSPACE', kind: 'inclusion', truthStatus: 'theorem', layer: 'randomized' },
  { id: 'ac0-subset-nc', source: 'AC0', target: 'NC', label: 'AC0 ⊆ NC', kind: 'inclusion', truthStatus: 'theorem', layer: 'circuit' },
  { id: 'nc-subset-p', source: 'NC', target: 'P', label: 'NC ⊆ P', kind: 'inclusion', truthStatus: 'theorem', layer: 'circuit' },
  { id: 'p-subset-ppoly', source: 'P', target: 'P/poly', label: 'P ⊆ P/poly', kind: 'inclusion', truthStatus: 'theorem', layer: 'circuit' },
  { id: '2sat-in-p', source: '2-SAT', target: 'P', label: '2-SAT ∈ P', kind: 'membership', truthStatus: 'theorem', layer: 'problem' },
  { id: 'sat-in-np', source: 'SAT', target: 'NP', label: 'SAT ∈ NP', kind: 'membership', truthStatus: 'theorem', layer: 'problem' },
  { id: 'sat-npc', source: 'SAT', target: 'NP-Complete', label: 'SAT ∈ NP-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: '3sat-npc', source: '3-SAT', target: 'NP-Complete', label: '3-SAT ∈ NP-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'clique-npc', source: 'CLIQUE', target: 'NP-Complete', label: 'CLIQUE ∈ NP-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'vc-npc', source: 'VERTEX-COVER', target: 'NP-Complete', label: 'VERTEX-COVER ∈ NP-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'subset-sum-npc', source: 'SUBSET-SUM', target: 'NP-Complete', label: 'SUBSET-SUM ∈ NP-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'tsp-npc', source: 'TSP Decision', target: 'NP-Complete', label: 'TSP ∈ NP-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'sat-3sat', source: 'SAT', target: '3-SAT', label: 'SAT ≤p 3-SAT', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: '3sat-clique', source: '3-SAT', target: 'CLIQUE', label: '3-SAT ≤p CLIQUE', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'vc-npc', source: 'VERTEX-COVER', target: 'NP-Complete', label: 'VERTEX-COVER es NP-completo', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'subset-sum-npc', source: 'SUBSET-SUM', target: 'NP-Complete', label: 'SUBSET-SUM es NP-completo', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'tsp-npc', source: 'TSP Decision', target: 'NP-Complete', label: 'TSP Decision es NP-completo', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'tautology-conp', source: 'TAUTOLOGY', target: 'co-NP', label: 'TAUTOLOGY ∈ co-NP', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'qbf-pspace', source: 'QBF', target: 'PSPACE', label: 'QBF ∈ PSPACE', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'parity-not-ac0', source: 'PARITY', target: 'AC0', label: 'PARITY ∉ AC0', kind: 'separation', truthStatus: 'theorem', layer: 'circuit' },
  { id: 'finite-subset-regular', source: 'Finite languages', target: 'Regular', label: 'Finite ⊆ Regular', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'regular-subset-dcfl', source: 'Regular', target: 'Deterministic Context-Free', label: 'Regular ⊆ DCFL', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'dcfl-subset-cfl', source: 'Deterministic Context-Free', target: 'Context-free', label: 'DCFL ⊆ CFL', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'cfl-subset-csl', source: 'Context-free', target: 'Context-sensitive', label: 'CFL ⊆ Context-sensitive', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'csl-subset-decidable', source: 'Context-sensitive', target: 'Decidable / Recursive', label: 'Context-sensitive ⊆ Decidable', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'lba-csl', source: 'LBA', target: 'Context-sensitive', label: 'LBA caracteriza CSL', kind: 'duality', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'exp-subset-expspace', source: 'EXP', target: 'EXPSPACE', label: 'EXPTIME ⊆ EXPSPACE', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'expspace-subset-decidable', source: 'EXPSPACE', target: 'Decidable / Recursive', label: 'EXPSPACE ⊆ Decidable', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'decidable-subset-re', source: 'Decidable / Recursive', target: 'Recognizable / RE', label: 'Decidable ⊆ RE', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'decidable-subset-core', source: 'Decidable / Recursive', target: 'co-RE', label: 'Decidable ⊆ co-RE', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 're-subset-finitely-describable', source: 'Recognizable / RE', target: 'Finitely describable', label: 'RE ⊆ Finitely describable', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'core-subset-finitely-describable', source: 'co-RE', target: 'Finitely describable', label: 'co-RE ⊆ Finitely describable', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'finitely-describable-subset-all', source: 'Finitely describable', target: 'All Languages', label: 'Finitely describable ⊆ All Languages', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'not-finitely-describable-subset-all', source: 'Not finitely describable', target: 'All Languages', label: 'Not finitely describable ⊆ All Languages', kind: 'inclusion', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'halting-in-re', source: 'Halting Problem / H', target: 'Recognizable / RE', label: 'H ∈ RE', kind: 'membership', truthStatus: 'theorem', layer: 'problem' },
  { id: 'halting-not-decidable', source: 'Halting Problem / H', target: 'Decidable / Recursive', label: 'H ∉ Decidable', kind: 'separation', truthStatus: 'theorem', layer: 'problem' },
  { id: 'hbar-not-re', source: 'Complement of Halting / Hbar', target: 'Recognizable / RE', label: 'H̄ ∉ RE', kind: 'separation', truthStatus: 'theorem', layer: 'problem' },
  { id: 'hbar-in-core', source: 'Complement of Halting / Hbar', target: 'co-RE', label: 'H̄ ∈ co-RE', kind: 'membership', truthStatus: 'theorem', layer: 'problem' },
  { id: 'halting-re-complete', source: 'Halting Problem / H', target: 'RE-complete', label: 'H ∈ RE-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 're-complete-subset-re', source: 'RE-complete', target: 'Recognizable / RE', label: 'RE-complete ⊆ RE', kind: 'inclusion', truthStatus: 'definition', layer: 'advanced' },
  { id: 'qbf-pspace-complete', source: 'QBF', target: 'PSPACE-complete', label: 'QBF ∈ PSPACE-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'pspace-complete-subset-pspace', source: 'PSPACE-complete', target: 'PSPACE', label: 'PSPACE-complete ⊆ PSPACE', kind: 'inclusion', truthStatus: 'definition', layer: 'advanced' },
  { id: 'go-exptime-complete', source: 'Go', target: 'EXPTIME-complete', label: 'Go ∈ EXPTIME-complete', kind: 'reduction', truthStatus: 'theorem', layer: 'problem' },
  { id: 'exptime-complete-subset-exp', source: 'EXPTIME-complete', target: 'EXP', label: 'EXPTIME-complete ⊆ EXPTIME', kind: 'inclusion', truthStatus: 'definition', layer: 'advanced' },
  { id: 'presburger-decidable', source: 'Presburger arithmetic', target: 'Decidable / Recursive', label: 'Presburger ∈ Decidable', kind: 'membership', truthStatus: 'theorem', layer: 'problem' },
  { id: 'undecidable-finitely-describable', source: 'Undecidable', target: 'Finitely describable', label: 'Undecidable ⊆ Finitely describable', kind: 'duality', truthStatus: 'theorem', layer: 'advanced' },
  { id: 'halting-undecidable', source: 'Halting Problem / H', target: 'Undecidable', label: 'H ∈ Undecidable', kind: 'membership', truthStatus: 'theorem', layer: 'problem' },
  { id: 'hbar-undecidable', source: 'Complement of Halting / Hbar', target: 'Undecidable', label: 'H̄ ∈ Undecidable', kind: 'membership', truthStatus: 'theorem', layer: 'problem' },
  { id: 'turing-degrees-undecidable', source: 'Turing degrees', target: 'Undecidable', label: 'Turing degrees ≤T ...', kind: 'duality', truthStatus: 'definition', layer: 'advanced' },
];
