import type { CodeReference, ComplexityProfile, ConceptNode } from './complexityTypes';

export type ComplexityConceptId =
  | 'P'
  | 'NP'
  | 'co-NP'
  | 'NP-Complete'
  | 'NP-Hard'
  | 'PSPACE'
  | 'EXP'
  | 'BPP'
  | 'RP'
  | 'ZPP'
  | 'P/poly'
  | 'AC0'
  | 'NC'
  | '2-SAT'
  | 'SAT'
  | '3-SAT'
  | 'CLIQUE'
  | 'VERTEX-COVER'
  | 'SUBSET-SUM'
  | 'TSP Decision'
  | 'TAUTOLOGY'
  | 'QBF'
  | 'PARITY'
  | 'All Languages'
  | 'Finitely describable'
  | 'Not finitely describable'
  | 'Recognizable / RE'
  | 'co-RE'
  | 'Decidable / Recursive'
  | 'Undecidable'
  | 'Halting Problem / H'
  | 'Complement of Halting / Hbar'
  | 'Turing degrees'
  | 'EXPSPACE'
  | 'Context-sensitive'
  | 'LBA'
  | 'Context-free'
  | 'Deterministic Context-Free'
  | 'Regular'
  | 'Finite languages'
  | 'Presburger arithmetic'
  | 'RE-complete'
  | 'EXPTIME-complete'
  | 'PSPACE-complete'
  | 'Go';

type ConceptDraft = Omit<ConceptNode, 'codeReferences'> & {
  codeReferences?: CodeReference[];
};

const polynomialProfile: ComplexityProfile = {
  shortLabel: 'Polynomial time',
  category: 'polynomial',
  highlights: ['O(log n)', 'O(n)', 'O(n log n)', 'O(n^2)'],
  note: 'Estas curvas ilustran crecimientos tipicos compatibles con clases o problemas tratables en tiempo polinomial.',
};

const npVerificationProfile: ComplexityProfile = {
  shortLabel: 'Verification in polynomial time',
  category: 'mixed',
  highlights: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(2^n)'],
  note: 'NP se define por verificacion polinomial, no por crecimiento exponencial. La curva exponencial es solo referencia de busqueda ingenua en algunos problemas.',
  warning: 'No es una prueba ni una caracterizacion exacta de toda NP.',
};

const bruteForceProfile: ComplexityProfile = {
  shortLabel: 'Brute-force reference',
  category: 'exponential',
  highlights: ['O(2^n)'],
  note: 'La curva exponencial representa una busqueda ingenua tipica sobre asignaciones o candidatos.',
  warning: 'Esto no prueba que no exista un algoritmo mejor.',
};

const circuitProfile: ComplexityProfile = {
  shortLabel: 'Circuit model',
  category: 'not_applicable',
  highlights: ['O(log n)', 'O(n)', 'O(n^2)'],
  note: 'Para circuitos, esta grafica es solo una analogia visual. El analisis real depende de tamano, profundidad, uniformidad y fan-in.',
  warning: 'No interpretes estas curvas como una clasificacion formal de clases de circuitos.',
};

const pspaceProfile: ComplexityProfile = {
  shortLabel: 'Space-bounded computation',
  category: 'not_applicable',
  highlights: ['O(2^n)'],
  note: 'PSPACE y QBF se entienden mejor por espacio polinomial y alternancia que por una unica curva temporal Big-O.',
  warning: 'La referencia exponencial es ilustrativa; PSPACE no se define por tiempo exponencial.',
};

function codeReferencesFor(concept: ConceptDraft): CodeReference[] {
  return [
    {
      label: 'Definicion del concepto',
      path: 'src/modules/complexity/complexityData.ts',
      module: 'Complexity Explorer',
      symbol: 'complexityConcepts',
      description: `Define el nodo ${concept.label}, su capa, estado de verdad, errores comunes, metadatos visuales, referencias de codigo y perfil de complejidad.`,
    },
    {
      label: 'Relaciones conceptuales',
      path: 'src/modules/complexity/complexityRelations.ts',
      module: 'Complexity Explorer',
      symbol: 'complexityRelations',
      description: `Declara las relaciones visuales donde ${concept.label} puede aparecer como origen o destino dentro del grafo.`,
    },
    {
      label: 'Renderizado visual',
      path: 'src/components/graph/ComplexityGraph.tsx',
      module: 'Graph Renderer',
      symbol: 'ComplexityGraph',
      description: 'Filtra capas, crea nodos React Flow, aplica badges de Truth Layer, tooltips cortos y estilos visuales.',
    },
    {
      label: 'Inspector derecho',
      path: 'src/components/layout/RightInspector.tsx',
      module: 'Inspector Panel',
      symbol: 'RightInspector',
      description: 'Muestra definicion ampliada, intuicion, ejemplos, errores comunes, perfil de complejidad y referencias de codigo.',
    },
    {
      label: 'Datos de errores comunes',
      path: 'src/modules/complexity/misconceptionsData.ts',
      module: 'Misconception Layer',
      symbol: 'misconceptions',
      description: `Define advertencias reutilizables relacionadas con ${concept.label}, severidad, correcciones y conceptos conectados.`,
    },
    {
      label: 'Panel de errores comunes',
      path: 'src/components/inspector/MisconceptionPanel.tsx',
      module: 'Inspector Panel',
      symbol: 'MisconceptionPanel',
      description: 'Renderiza la capa global de errores comunes cuando el toggle esta activo y muestra contador discreto cuando esta inactivo.',
    },
    ...(concept.codeReferences ?? []),
  ];
}

function withReferences(concept: ConceptDraft): ConceptNode {
  return {
    ...concept,
    codeReferences: codeReferencesFor(concept),
  };
}

export const complexityConcepts: ConceptNode[] = [
  withReferences({
    id: 'P',
    label: 'P',
    kind: 'class',
    layer: 'basic',
    shortDefinition: 'P: problemas resolubles en tiempo polinomial por algoritmos deterministas.',
    definition: 'P es la clase de problemas de decision que pueden resolverse por una maquina determinista en tiempo polinomial. Es el punto de referencia formal para lo que suele llamarse computacion eficiente en teoria de la complejidad. P esta contenido en NP porque una solucion que puede encontrarse eficientemente tambien puede verificarse eficientemente. No debe confundirse con facilidad practica absoluta: un polinomio enorme puede seguir siendo inutil en la practica.',
    intuition: 'Representa la region donde conocemos procedimientos generales cuyo costo crece de forma polinomial con el tamano de entrada.',
    examples: ['2-SAT', 'alcanzabilidad en grafos', 'ordenamiento'],
    commonErrors: ['P significa problemas faciles en sentido absoluto.'],
    corrections: ['P significa tratables bajo el modelo asintotico polinomial; un polinomio enorme puede ser impractico.'],
    truthStatus: 'definition',
    codeSnippetId: 'P',
    misconceptionIds: ['p-fast-in-practice'],
    complexityProfile: {
      ...polynomialProfile,
      note: 'P agrupa problemas resolubles en tiempo polinomial. Estas curvas ilustran crecimientos tipicos compatibles con esa clase.',
    },
    accent: 'green',
    position: { x: 110, y: 250 },
  }),
  withReferences({
    id: 'NP',
    label: 'NP',
    kind: 'class',
    layer: 'basic',
    shortDefinition: 'NP: problemas cuyas soluciones si pueden verificarse en tiempo polinomial.',
    definition: 'NP es la clase de problemas de decision para los cuales, si la respuesta es si, existe un certificado verificable en tiempo polinomial por una maquina determinista. No significa no polinomial. Su importancia esta en que muchos problemas naturales tienen soluciones faciles de comprobar aunque no sepamos si son faciles de encontrar. La pregunta P vs NP pregunta si todo problema verificable eficientemente tambien puede resolverse eficientemente.',
    intuition: 'Piensa en una prueba corta: encontrarla puede ser dificil, pero comprobarla debe ser eficiente.',
    examples: ['SAT', '3-SAT', 'CLIQUE', 'SUBSET-SUM'],
    commonErrors: ['NP significa no polinomial.'],
    corrections: ['No. NP significa que una solucion propuesta puede verificarse en tiempo polinomial.'],
    truthStatus: 'definition',
    codeSnippetId: 'NP',
    misconceptionIds: ['np-means-non-polynomial'],
    complexityProfile: npVerificationProfile,
    accent: 'cyan',
    position: { x: 360, y: 250 },
  }),
  withReferences({
    id: 'co-NP',
    label: 'co-NP',
    kind: 'class',
    layer: 'basic',
    shortDefinition: 'co-NP: problemas cuyos complementos estan en NP.',
    definition: 'co-NP contiene problemas cuyos complementos pertenecen a NP. Intuitivamente, si NP captura certificados eficientes para respuestas si, co-NP captura certificados eficientes para negar una instancia mediante el complemento. Se sabe que P esta contenido tanto en NP como en co-NP, pero no se sabe si NP = co-NP. No debe asumirse que co-NP sea simplemente lo mismo que NP.',
    intuition: 'Donde NP mira certificados de existencia, co-NP mira certificados asociados a universalidad o refutacion.',
    examples: ['TAUTOLOGY', 'UNSAT'],
    commonErrors: ['NP y co-NP son lo mismo.'],
    corrections: ['No se sabe si NP = co-NP. Si NP != co-NP, entonces P != NP.'],
    truthStatus: 'definition',
    codeSnippetId: 'co-NP',
    misconceptionIds: ['np-conp-obviously-same'],
    complexityProfile: npVerificationProfile,
    accent: 'purple',
    position: { x: 360, y: 450 },
  }),
  withReferences({
    id: 'NP-Complete',
    label: 'NP-Complete',
    kind: 'class',
    layer: 'basic',
    shortDefinition: 'NP-Complete: problemas en NP que son al menos tan dificiles como todo NP.',
    definition: 'Un problema NP-completo pertenece a NP y ademas es NP-hard bajo reducciones polinomiales. Esto significa que cualquier problema en NP puede transformarse en el en tiempo polinomial. Si se encontrara un algoritmo polinomial para un solo problema NP-completo, entonces todos los problemas de NP tendrian algoritmos polinomiales y se probaria P = NP. No significa imposible; significa que representa el nucleo mas dificil conocido dentro de NP.',
    intuition: 'Es el punto de maxima presion dentro de NP: una solucion eficiente ahi propagaria eficiencia a toda la clase.',
    examples: ['SAT', '3-SAT', 'CLIQUE', 'VERTEX-COVER', 'SUBSET-SUM'],
    commonErrors: ['NP-completo significa imposible.'],
    corrections: ['No. Significa que esta en NP y es NP-hard. No se sabe si tiene o no algoritmo polinomial.'],
    truthStatus: 'definition',
    codeSnippetId: 'NP-Complete',
    misconceptionIds: ['np-complete-impossible'],
    complexityProfile: bruteForceProfile,
    accent: 'red',
    position: { x: 640, y: 300 },
  }),
  withReferences({
    id: 'NP-Hard',
    label: 'NP-Hard',
    kind: 'class',
    layer: 'basic',
    shortDefinition: 'NP-Hard: al menos tan dificil como los problemas de NP.',
    definition: 'NP-hard describe problemas a los que todo problema de NP puede reducirse bajo una nocion de reduccion dada, normalmente polinomial. A diferencia de NP-completo, un problema NP-hard no tiene que pertenecer a NP ni ser un problema de decision. Esta clase permite hablar de dureza para optimizacion, conteo o incluso problemas fuera de NP. No debe confundirse con estar dentro de NP.',
    intuition: 'Es una etiqueta de dureza comparativa, no una garantia de verificabilidad eficiente.',
    examples: ['TSP Optimization', 'problemas indecidibles bajo reducciones apropiadas'],
    commonErrors: ['NP-hard siempre esta dentro de NP.'],
    corrections: ['No necesariamente. Un problema NP-hard puede estar fuera de NP.'],
    truthStatus: 'definition',
    codeSnippetId: 'NP-Hard',
    misconceptionIds: ['np-hard-inside-np'],
    complexityProfile: bruteForceProfile,
    accent: 'yellow',
    position: { x: 900, y: 300 },
  }),
  withReferences({
    id: 'PSPACE',
    label: 'PSPACE',
    kind: 'class',
    layer: 'basic',
    shortDefinition: 'PSPACE: problemas decidibles usando espacio polinomial.',
    definition: 'PSPACE es la clase de problemas decidibles usando una cantidad polinomial de memoria, sin exigir que el tiempo tambien sea polinomial. Contiene a P, NP y co-NP mediante inclusiones conocidas. Es central para problemas con alternancia, juegos y formulas cuantificadas como QBF. No debe confundirse con problemas necesariamente rapidos: reutilizar memoria no impide que el tiempo sea enorme.',
    intuition: 'La memoria queda acotada, pero el proceso puede explorar arboles profundos reutilizando espacio.',
    examples: ['QBF', 'juegos finitos generalizados'],
    commonErrors: ['PSPACE solo contiene problemas practicos porque usa espacio polinomial.'],
    corrections: ['El espacio puede ser polinomial, pero el tiempo puede crecer exponencialmente.'],
    truthStatus: 'definition',
    codeSnippetId: 'PSPACE',
    complexityProfile: pspaceProfile,
    accent: 'purple',
    position: { x: 640, y: 100 },
  }),
  withReferences({
    id: 'EXP',
    label: 'EXPTIME / EXP',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'EXP: problemas resolubles en tiempo exponencial determinista.',
    definition: 'EXP contiene problemas decidibles por algoritmos deterministas en tiempo exponencial. Es una clase formal, no solo una palabra informal para lento. PSPACE esta contenido en EXP por simulaciones conocidas, mientras que P esta estrictamente contenido en EXP por el teorema de jerarquia temporal. No debe confundirse con NP: NP se define por verificacion polinomial, no por busqueda exponencial.',
    intuition: 'Marca una region donde se permite tiempo mucho mayor que el polinomial, pero todavia computable bajo una cota formal.',
    examples: ['juegos con horizonte exponencial', 'versiones succinct de problemas clasicos'],
    commonErrors: ['EXP es solo una forma informal de decir muy lento.'],
    corrections: ['EXP es una clase formal con cotas exponenciales precisas de tiempo determinista.'],
    truthStatus: 'definition',
    codeSnippetId: 'EXP',
    complexityProfile: bruteForceProfile,
    accent: 'yellow',
    position: { x: 900, y: 80 },
  }),
  withReferences({
    id: 'BPP',
    label: 'BPP',
    kind: 'class',
    layer: 'randomized',
    shortDefinition: 'BPP: tiempo polinomial probabilistico con error acotado.',
    definition: 'BPP contiene problemas resolubles en tiempo polinomial por algoritmos aleatorizados con probabilidad de error acotada. El error puede reducirse repitiendo el algoritmo, por lo que no representa una aceptacion sin control de respuestas inciertas. Es importante para estudiar el poder de la aleatoriedad frente a modelos deterministas. No debe confundirse con NP: BPP habla de algoritmos probabilisticos, no de certificados.',
    intuition: 'Usa azar como recurso computacional, manteniendo control estadistico sobre la respuesta.',
    examples: ['primalidad historicamente via tests probabilisticos', 'identidad polinomial aleatorizada'],
    commonErrors: ['BPP significa aceptar resultados probablemente correctos sin control.'],
    corrections: ['El error esta acotado y puede amplificarse repitiendo el algoritmo.'],
    truthStatus: 'definition',
    codeSnippetId: 'BPP',
    complexityProfile: polynomialProfile,
    accent: 'cyan',
    position: { x: 90, y: 620 },
  }),
  withReferences({
    id: 'RP',
    label: 'RP',
    kind: 'class',
    layer: 'randomized',
    shortDefinition: 'RP: tiempo polinomial aleatorizado con error unilateral.',
    definition: 'RP es una clase aleatorizada de tiempo polinomial con error unilateral. Para instancias negativas, el algoritmo no debe aceptar incorrectamente; para instancias positivas puede fallar con probabilidad acotada. Esto la distingue de BPP, donde puede haber error bilateral. Es una forma precisa de estudiar busqueda probabilistica con garantias asimetricas.',
    intuition: 'Un si encontrado por azar es confiable, pero puede hacer falta repetir para encontrarlo.',
    examples: ['tests aleatorizados con falsos negativos'],
    commonErrors: ['RP y BPP son exactamente lo mismo.'],
    corrections: ['RP tiene error unilateral; BPP permite error bilateral acotado.'],
    truthStatus: 'definition',
    codeSnippetId: 'RP',
    complexityProfile: polynomialProfile,
    accent: 'green',
    position: { x: 320, y: 650 },
  }),
  withReferences({
    id: 'ZPP',
    label: 'ZPP',
    kind: 'class',
    layer: 'randomized',
    shortDefinition: 'ZPP: algoritmos aleatorizados de cero error y tiempo esperado polinomial.',
    definition: 'ZPP captura problemas resolubles por algoritmos aleatorizados que nunca devuelven una respuesta incorrecta y cuyo tiempo esperado es polinomial. Es la clase asociada a algoritmos Las Vegas. La aleatoriedad afecta el tiempo de ejecucion, no la correccion de la respuesta. No debe confundirse con determinismo: el azar sigue siendo parte del procedimiento.',
    intuition: 'Puede tardar mas o menos segun las monedas, pero cuando termina, la respuesta es correcta.',
    examples: ['algoritmos Las Vegas'],
    commonErrors: ['ZPP no usa azar porque no comete errores.'],
    corrections: ['Usa azar para controlar tiempo esperado, no para permitir respuestas incorrectas.'],
    truthStatus: 'definition',
    codeSnippetId: 'ZPP',
    complexityProfile: polynomialProfile,
    accent: 'purple',
    position: { x: 540, y: 650 },
  }),
  withReferences({
    id: 'AC0',
    label: 'AC0',
    kind: 'class',
    layer: 'circuit',
    shortDefinition: 'AC0: circuitos de profundidad constante y tamano polinomial.',
    definition: 'AC0 es una clase de circuitos booleanos de profundidad constante, tamano polinomial y compuertas AND, OR y NOT con fan-in no acotado para AND/OR. Es un modelo restringido de computo paralelo. Se conocen limites inferiores fuertes para AC0, como que PARITY no pertenece a AC0. Esto no resuelve P vs NP porque AC0 es mucho mas debil que los modelos generales de computacion.',
    intuition: 'Muchas puertas trabajan en paralelo, pero hay muy pocas capas para propagar informacion global.',
    examples: ['operaciones booleanas locales simples', 'PARITY no pertenece a AC0'],
    commonErrors: ['Probar limites inferiores para AC0 resuelve P vs NP.'],
    corrections: ['No. AC0 es un modelo restringido. Un limite inferior ahi no separa automaticamente P de NP.'],
    truthStatus: 'definition',
    codeSnippetId: 'AC0',
    misconceptionIds: ['ac0-lower-bound-solves-pnp'],
    complexityProfile: {
      ...circuitProfile,
      note: 'AC0 pertenece al mundo de circuitos. El grafico Big-O es una analogia limitada; el analisis real depende de profundidad constante, tamano, uniformidad y fan-in.',
    },
    accent: 'red',
    position: { x: 90, y: 830 },
  }),
  withReferences({
    id: 'NC',
    label: 'NC',
    kind: 'class',
    layer: 'circuit',
    shortDefinition: 'NC: problemas eficientemente paralelizables.',
    definition: 'NC contiene problemas resolubles por familias de circuitos de tamano polinomial y profundidad polilogaritmica. Sirve como modelo teorico de computacion paralela eficiente. Se sabe que NC esta contenido en P, pero no se sabe si todo problema de P es altamente paralelizable. No debe confundirse eficiencia secuencial con paralelizacion eficiente.',
    intuition: 'Si el trabajo puede organizarse en pocas rondas paralelas, el problema se acerca al espiritu de NC.',
    examples: ['suma paralela', 'multiplicacion matricial en variantes de NC'],
    commonErrors: ['NC contiene exactamente los mismos problemas que P.'],
    corrections: ['Se sabe NC esta contenido en P, pero no se sabe si NC = P.'],
    truthStatus: 'definition',
    codeSnippetId: 'NC',
    complexityProfile: circuitProfile,
    accent: 'cyan',
    position: { x: 320, y: 830 },
  }),
  withReferences({
    id: 'P/poly',
    label: 'P/poly',
    kind: 'class',
    layer: 'circuit',
    shortDefinition: 'P/poly: circuitos no uniformes de tamano polinomial.',
    definition: 'P/poly contiene lenguajes decidibles por familias de circuitos de tamano polinomial, potencialmente no uniformes. Puede interpretarse como computacion polinomial con una cadena de consejo distinta para cada longitud de entrada. Es relevante para barreras y relaciones entre circuitos y clases clasicas. No debe confundirse con P, porque la no uniformidad cambia sustancialmente el modelo.',
    intuition: 'Cada tamano de entrada puede traer su propio circuito preparado de antemano.',
    examples: ['familias no uniformes de circuitos polinomiales'],
    commonErrors: ['P/poly es simplemente P escrito con circuitos.'],
    corrections: ['P/poly permite no uniformidad; puede contener lenguajes no decidibles si no se exige uniformidad.'],
    truthStatus: 'definition',
    codeSnippetId: 'P/poly',
    complexityProfile: circuitProfile,
    accent: 'yellow',
    position: { x: 560, y: 830 },
  }),
  withReferences({
    id: '2-SAT',
    label: '2-SAT',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: '2-SAT: satisfacibilidad de formulas CNF con clausulas de hasta dos literales.',
    definition: '2-SAT pregunta si una formula CNF con clausulas de a lo sumo dos literales es satisfacible. Aunque pertenece a la familia de problemas SAT, su estructura permite algoritmos polinomiales basados en grafos de implicacion y componentes fuertemente conexas. Es un buen ejemplo de como una restriccion sintactica puede cambiar la complejidad. No debe confundirse con 3-SAT, que es NP-completo.',
    intuition: 'La restriccion a pares transforma las clausulas en implicaciones que pueden analizarse con estructura de grafo.',
    examples: ['implication graph', 'restricciones binarias'],
    commonErrors: ['2-SAT es dificil porque SAT es dificil.'],
    corrections: ['No. 2-SAT esta en P; la restriccion a dos literales cambia la estructura.'],
    truthStatus: 'theorem',
    codeSnippetId: '2-SAT',
    complexityProfile: {
      ...polynomialProfile,
      note: '2-SAT pertenece a P. La curva polinomial resaltada representa que existen algoritmos eficientes para resolverlo.',
    },
    accent: 'green',
    position: { x: 120, y: 40 },
  }),
  withReferences({
    id: 'SAT',
    label: 'SAT',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'SAT: decidir si una formula booleana tiene una asignacion satisfactoria.',
    definition: 'SAT pregunta si existe una asignacion de valores booleanos que haga verdadera una formula. Esta en NP porque una asignacion candidata se verifica en tiempo polinomial. Por el teorema de Cook-Levin, SAT es NP-completo y ocupa un lugar central en P vs NP. No debe confundirse la dificultad de encontrar una asignacion con la facilidad de verificar una propuesta.',
    intuition: 'El espacio de asignaciones puede ser enorme, pero comprobar una asignacion concreta es directo.',
    examples: ['CNF-SAT', 'formulas booleanas generales'],
    commonErrors: ['SAT no esta en NP porque encontrar la asignacion puede ser dificil.'],
    corrections: ['SAT esta en NP porque una asignacion propuesta se verifica en tiempo polinomial.'],
    truthStatus: 'theorem',
    codeSnippetId: 'SAT',
    misconceptionIds: ['sat-in-np-means-in-p'],
    complexityProfile: {
      ...bruteForceProfile,
      note: 'La curva O(2^n) representa fuerza bruta tipica sobre asignaciones para SAT, no una caracterizacion completa de SAT.',
    },
    accent: 'red',
    position: { x: 570, y: 500 },
  }),
  withReferences({
    id: '3-SAT',
    label: '3-SAT',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: '3-SAT: SAT restringido a clausulas de tres literales.',
    definition: '3-SAT restringe SAT a formulas CNF con tres literales por clausula y aun asi sigue siendo NP-completo. Su importancia es que muestra que la dureza de SAT persiste bajo una forma sintactica muy controlada. La busqueda ingenua sobre asignaciones crece exponencialmente, pero eso solo describe un algoritmo concreto. No demuestra que no exista un algoritmo polinomial.',
    intuition: 'Pocos literales por clausula no eliminan la capacidad de codificar restricciones dificiles.',
    examples: ['reducciones desde SAT', 'gadgets booleanos'],
    commonErrors: ['Si fuerza bruta tarda mucho, entonces P != NP.'],
    corrections: ['No. Eso solo muestra que ese algoritmo especifico escala mal. No demuestra que no exista un algoritmo polinomial.'],
    truthStatus: 'theorem',
    codeSnippetId: '3-SAT',
    misconceptionIds: ['3sat-bruteforce-does-not-prove-pneqnp'],
    complexityProfile: {
      ...bruteForceProfile,
      note: 'La fuerza bruta para 3-SAT crece exponencialmente al probar asignaciones, pero la NP-completitud se justifica por reducciones.',
    },
    accent: 'red',
    position: { x: 760, y: 500 },
  }),
  withReferences({
    id: 'CLIQUE',
    label: 'CLIQUE',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'CLIQUE: decidir si un grafo contiene un subgrafo completo de tamano k.',
    definition: 'CLIQUE pregunta si un grafo tiene un conjunto de al menos k vertices todos conectados entre si. Esta en NP porque el conjunto de vertices sirve como certificado verificable rapidamente. Es NP-completo mediante reducciones polinomiales, por lo que conecta teoria de grafos con P vs NP. No debe confundirse el tamano grande de un grafo con una prueba de dureza formal.',
    intuition: 'Buscar el grupo correcto puede ser costoso, pero verificar un grupo propuesto es mecanico.',
    examples: ['redes de compatibilidad', 'subgrafos completos'],
    commonErrors: ['CLIQUE es dificil porque los grafos son grandes, no por reducciones.'],
    corrections: ['La dificultad NP-completa es una afirmacion formal via reducciones polinomiales.'],
    truthStatus: 'theorem',
    codeSnippetId: 'CLIQUE',
    complexityProfile: bruteForceProfile,
    accent: 'red',
    position: { x: 950, y: 500 },
  }),
  withReferences({
    id: 'VERTEX-COVER',
    label: 'VERTEX-COVER',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'VERTEX-COVER: cubrir todas las aristas con k vertices.',
    definition: 'VERTEX-COVER pregunta si existe un conjunto de k vertices que toque todas las aristas de un grafo. Esta en NP porque un conjunto candidato se verifica revisando cada arista. Es NP-completo y esta estrechamente relacionado con CLIQUE e Independent Set mediante complementos y transformaciones. No es exactamente el mismo problema que CLIQUE aunque compartan reducciones cercanas.',
    intuition: 'En vez de buscar vertices todos conectados, busca vertices que intercepten todas las conexiones.',
    examples: ['cobertura de relaciones', 'reduccion desde CLIQUE'],
    commonErrors: ['VERTEX-COVER y CLIQUE son el mismo problema.'],
    corrections: ['Estan estrechamente relacionados por complemento, pero sus instancias y certificados se formulan distinto.'],
    truthStatus: 'theorem',
    codeSnippetId: 'VERTEX-COVER',
    complexityProfile: bruteForceProfile,
    accent: 'yellow',
    position: { x: 950, y: 650 },
  }),
  withReferences({
    id: 'SUBSET-SUM',
    label: 'SUBSET-SUM',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'SUBSET-SUM: decidir si algun subconjunto suma un objetivo.',
    definition: 'SUBSET-SUM pregunta si existe un subconjunto de numeros cuya suma sea exactamente un valor objetivo. Esta en NP porque el subconjunto elegido es un certificado verificable rapidamente. Es NP-completo cuando los numeros forman parte de la entrada en representacion binaria. No debe confundirse un algoritmo pseudo-polinomial con un algoritmo polinomial en el tamano real de la entrada.',
    intuition: 'La dificultad surge de combinar muchas decisiones binarias con numeros codificados compactamente.',
    examples: ['mochila', 'particion'],
    commonErrors: ['Programacion dinamica pseudo-polinomial implica que SUBSET-SUM esta en P.'],
    corrections: ['Pseudo-polinomial no es polinomial en el tamano binario de la entrada.'],
    truthStatus: 'theorem',
    codeSnippetId: 'SUBSET-SUM',
    complexityProfile: bruteForceProfile,
    accent: 'yellow',
    position: { x: 760, y: 650 },
  }),
  withReferences({
    id: 'TSP Decision',
    label: 'TSP Decision',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'TSP Decision: decidir si existe un tour con costo acotado.',
    definition: 'TSP Decision pregunta si existe un recorrido que visite todas las ciudades y tenga costo a lo sumo una cota B. La version de decision esta en NP porque un tour propuesto puede verificarse sumando sus costos. Es NP-completa, mientras que la version de optimizacion se clasifica como NP-hard. No debe mezclarse la pregunta de decision con pedir directamente el tour optimo.',
    intuition: 'La decision convierte un problema de optimizacion en una pregunta si/no adecuada para NP.',
    examples: ['rutas con cota de costo', 'Hamiltonian cycle con pesos'],
    commonErrors: ['TSP siempre significa la version de optimizacion.'],
    corrections: ['Para NP-completitud se usa la version de decision; la version de optimizacion es NP-hard.'],
    truthStatus: 'theorem',
    codeSnippetId: 'TSP Decision',
    complexityProfile: bruteForceProfile,
    accent: 'yellow',
    position: { x: 1160, y: 500 },
  }),
  withReferences({
    id: 'TAUTOLOGY',
    label: 'TAUTOLOGY',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'TAUTOLOGY: decidir si una formula es verdadera en todas las asignaciones.',
    definition: 'TAUTOLOGY pregunta si una formula booleana es verdadera bajo toda asignacion posible. Su complemento pregunta si existe una asignacion que la falsifique, por lo que se relaciona naturalmente con co-NP. Es co-NP-completo bajo reducciones estandar. No debe asumirse que esta en NP por analogia directa con SAT; esa afirmacion dependeria de preguntas abiertas sobre NP y co-NP.',
    intuition: 'SAT busca un testigo de verdad; TAUTOLOGY exige resistir todos los contraejemplos.',
    examples: ['validez proposicional'],
    commonErrors: ['TAUTOLOGY esta en NP por la misma razon que SAT.'],
    corrections: ['TAUTOLOGY esta naturalmente en co-NP; su complemento esta en NP.'],
    truthStatus: 'theorem',
    codeSnippetId: 'TAUTOLOGY',
    complexityProfile: bruteForceProfile,
    accent: 'purple',
    position: { x: 570, y: 720 },
  }),
  withReferences({
    id: 'QBF',
    label: 'QBF',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'QBF: verdad de formulas booleanas con cuantificadores.',
    definition: 'QBF decide la verdad de formulas booleanas con cuantificadores existenciales y universales. Es PSPACE-completo y sirve como problema canonico para estudiar espacio polinomial y alternancia. Generaliza SAT al permitir juegos de eleccion entre cuantificadores, lo que cambia la naturaleza de la complejidad. No debe verse como solo SAT con sintaxis adicional.',
    intuition: 'La alternancia de cuantificadores se comporta como un arbol de juego entre existe y para todo.',
    examples: ['TQBF', 'juegos finitos'],
    commonErrors: ['QBF es solo SAT con sintaxis extra.'],
    corrections: ['La alternancia de cuantificadores eleva la complejidad hasta PSPACE-completo.'],
    truthStatus: 'theorem',
    codeSnippetId: 'QBF',
    misconceptionIds: ['qbf-just-sat-more-vars'],
    complexityProfile: {
      ...pspaceProfile,
      note: 'QBF es PSPACE-completo. Esta tarjeta es una referencia visual limitada porque el punto central es espacio polinomial y alternancia, no una curva temporal unica.',
    },
    accent: 'purple',
    position: { x: 820, y: 120 },
  }),
  withReferences({
    id: 'PARITY',
    label: 'PARITY',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'PARITY: decidir si el numero de unos de la entrada es impar.',
    definition: 'PARITY decide si la cantidad de bits 1 en una entrada es impar. Es facil en modelos secuenciales usuales y pertenece a P, pero no pertenece a AC0, lo que da un limite inferior fuerte para circuitos de profundidad constante. Es importante porque separa un problema simple de un modelo restringido. No debe concluirse que PARITY este fuera de P.',
    intuition: 'Una propiedad global sencilla puede ser invisible para circuitos demasiado poco profundos.',
    examples: ['xor de n bits', 'limite inferior para AC0'],
    commonErrors: ['PARITY fuera de AC0 significa PARITY fuera de P.'],
    corrections: ['No. PARITY esta en P; el limite inferior solo aplica al modelo AC0.'],
    truthStatus: 'theorem',
    codeSnippetId: 'PARITY',
    misconceptionIds: ['parity-not-ac0-not-p'],
    complexityProfile: circuitProfile,
    accent: 'green',
    position: { x: 100, y: 1010 },
  }),
  withReferences({
    id: 'All Languages',
    label: 'All Languages / 2^Σ*',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Todos los lenguajes sobre un alfabeto: el conjunto potencia de Σ*.',
    definition: 'All Languages / 2^Σ* contiene todos los subconjuntos posibles de cadenas sobre un alfabeto fijo. Es inmensamente mas grande que la coleccion de lenguajes que pueden describirse finitamente por programas, gramaticas o formulas. Sirve para separar el universo semantico de todos los lenguajes del universo sintactico de objetos finitos.',
    intuition: 'La mayoria de los lenguajes existen como subconjuntos abstractos, pero no tienen descripcion finita.',
    examples: ['cualquier subconjunto de Σ*', 'lenguajes no describibles finitamente'],
    commonErrors: ['Todo lenguaje tiene algun programa que lo decide o reconoce.'],
    corrections: ['No. Hay incontablemente muchos lenguajes, pero solo contablemente muchas descripciones finitas.'],
    truthStatus: 'definition',
    accent: 'purple',
    position: { x: -980, y: -260 },
  }),
  withReferences({
    id: 'Finitely describable',
    label: 'Finitely describable',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes especificables por una descripcion finita.',
    definition: 'Los lenguajes finitamente describibles son aquellos que pueden nombrarse mediante algun objeto finito: una maquina, una gramatica, una formula o una definicion formal. Esta coleccion es contable y por tanto no cubre todos los lenguajes de 2^Σ*.',
    intuition: 'Todo lo que puede aparecer en un libro, programa o archivo finito cae aqui.',
    examples: ['lenguajes decidibles', 'lenguajes reconocibles', 'gramaticas formales'],
    commonErrors: ['Finitamente describible significa decidible.'],
    corrections: ['No. El Halting Problem es finitamente describible y reconocible, pero no decidible.'],
    truthStatus: 'definition',
    misconceptionIds: ['finitely-describable-means-decidable'],
    accent: 'cyan',
    position: { x: -720, y: -160 },
  }),
  withReferences({
    id: 'Not finitely describable',
    label: 'Not finitely describable',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes sin descripcion finita posible.',
    definition: 'Los lenguajes no finitamente describibles existen por cardinalidad: hay mas subconjuntos de Σ* que cadenas finitas que puedan describirlos. No son lenguajes que simplemente no hayamos encontrado; formalmente no pueden capturarse por ninguna descripcion finita.',
    intuition: 'La mayor parte del universo de lenguajes queda fuera de cualquier formalismo finito.',
    examples: ['lenguajes arbitrarios no computables por cardinalidad'],
    commonErrors: ['No finitely describable significa muy dificil pero eventualmente programable.'],
    corrections: ['No. Significa que no existe ninguna descripcion finita dentro del modelo de codificacion.'],
    truthStatus: 'theorem',
    misconceptionIds: ['not-finitely-describable-programmable'],
    accent: 'red',
    position: { x: -720, y: -360 },
  }),
  withReferences({
    id: 'Recognizable / RE',
    label: 'Recognizable / RE',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes reconocibles por una maquina de Turing.',
    definition: 'Un lenguaje es reconocible, recursivamente enumerable o RE si existe una maquina de Turing que acepta exactamente las cadenas del lenguaje, aunque pueda no detenerse fuera de el. RE contiene a todos los lenguajes decidibles, pero tambien contiene problemas indecidibles como Halting.',
    intuition: 'Hay un procedimiento que confirma los si, pero puede quedarse corriendo para los no.',
    examples: ['Halting Problem', 'lenguajes enumerables por programas'],
    commonErrors: ['Reconocible significa decidible.'],
    corrections: ['No. Reconocible solo garantiza detenerse y aceptar en instancias positivas.'],
    truthStatus: 'definition',
    misconceptionIds: ['recognizable-means-decidable'],
    accent: 'green',
    position: { x: -460, y: -120 },
  }),
  withReferences({
    id: 'co-RE',
    label: 'co-RE',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Complementos de lenguajes reconocibles.',
    definition: 'co-RE contiene lenguajes cuyo complemento es reconocible. Un lenguaje es decidible exactamente cuando pertenece tanto a RE como a co-RE. Esta clase permite expresar problemas donde se puede reconocer evidencia de no-pertenencia.',
    intuition: 'Si RE confirma los si, co-RE confirma los no mediante el complemento.',
    examples: ['complementos de lenguajes RE', 'Complement of Halting esta en co-RE'],
    commonErrors: ['RE y co-RE son automaticamente iguales.'],
    corrections: ['No. Si RE = co-RE, entonces Halting seria decidible; se sabe que no lo es.'],
    truthStatus: 'definition',
    accent: 'purple',
    position: { x: -230, y: -270 },
  }),
  withReferences({
    id: 'Decidable / Recursive',
    label: 'Decidable / Recursive',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes decidibles por una maquina que siempre se detiene.',
    definition: 'Un lenguaje decidible o recursivo tiene una maquina de Turing que se detiene en toda entrada y responde correctamente si o no. Es una nocion mas fuerte que reconocibilidad. Las clases P, NP, PSPACE, EXP y EXPSPACE son subclases de los lenguajes decidibles.',
    intuition: 'Siempre hay respuesta final, tanto para pertenencia como para no-pertenencia.',
    examples: ['Regular', 'Context-free', 'QBF', 'Presburger arithmetic'],
    commonErrors: ['Si un problema tiene descripcion formal, entonces es decidible.'],
    corrections: ['No. Halting esta formalmente descrito, pero no es decidible.'],
    truthStatus: 'definition',
    misconceptionIds: ['formal-description-implies-decidable'],
    accent: 'green',
    position: { x: -20, y: -80 },
  }),
  withReferences({
    id: 'Undecidable',
    label: 'Undecidable',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Problemas sin algoritmo total de decision.',
    definition: 'Un problema indecidible no tiene algoritmo que siempre se detenga y responda correctamente para toda entrada. Puede ser reconocible, co-reconocible o estar fuera de ambas clases. Halting es el ejemplo canonico de problema reconocible pero no decidible.',
    intuition: 'No es solo dificil; no existe decidor general.',
    examples: ['Halting Problem', 'Post correspondence problem'],
    commonErrors: ['Indecidible significa que todas las instancias son imposibles de resolver.'],
    corrections: ['No. Puede haber muchas instancias resolubles; lo imposible es un algoritmo total para todas.'],
    truthStatus: 'definition',
    accent: 'red',
    position: { x: -210, y: 80 },
  }),
  withReferences({
    id: 'Halting Problem / H',
    label: 'Halting Problem / H',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'Decidir si un programa se detiene en una entrada.',
    definition: 'El Halting Problem pregunta si una maquina de Turing se detiene en una entrada dada. Es reconocible porque se puede simular y aceptar cuando la maquina se detiene, pero no es decidible. Es un ejemplo central de frontera entre reconocibilidad y decidibilidad.',
    intuition: 'Podemos ver que un programa se detuvo cuando ocurre; no siempre podemos saber de antemano si nunca lo hara.',
    examples: ['RE-complete → Halting Problem', 'simulacion universal'],
    commonErrors: ['Halting no es reconocible porque es indecidible.'],
    corrections: ['No. Halting es reconocible pero no decidible.'],
    truthStatus: 'theorem',
    misconceptionIds: ['halting-undecidable-not-recognizable'],
    accent: 'red',
    position: { x: -470, y: 80 },
  }),
  withReferences({
    id: 'Complement of Halting / Hbar',
    label: 'Complement of Halting / H̄',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'El complemento del Halting Problem.',
    definition: 'El complemento de Halting contiene pares maquina-entrada donde la maquina no se detiene. No es reconocible: si tanto Halting como su complemento fueran reconocibles, Halting seria decidible ejecutando ambos reconocedores en paralelo.',
    intuition: 'Confirmar que algo nunca ocurrira no puede hacerse esperando una señal positiva general.',
    examples: ['H̄ ∉ RE', 'H̄ ∈ co-RE'],
    commonErrors: ['El complemento de un lenguaje RE tambien debe ser RE.'],
    corrections: ['No. RE no esta cerrada bajo complemento; H̄ no es RE.'],
    truthStatus: 'theorem',
    misconceptionIds: ['re-closed-under-complement'],
    accent: 'yellow',
    position: { x: -470, y: 260 },
  }),
  withReferences({
    id: 'Turing degrees',
    label: 'Turing degrees',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Clasificacion de problemas por reducibilidad de Turing.',
    definition: 'Los grados de Turing agrupan problemas con el mismo poder computacional bajo reducciones con oraculos. Permiten distinguir niveles de indecidibilidad mas alla de decidible versus indecidible.',
    intuition: 'No todos los problemas indecidibles tienen la misma dificultad computacional.',
    examples: ['grado de Halting', 'jerarquias de oraculos'],
    commonErrors: ['Todos los indecidibles son equivalentes.'],
    corrections: ['No. Los grados de Turing refinan la estructura de la indecidibilidad.'],
    truthStatus: 'definition',
    accent: 'purple',
    position: { x: -700, y: 160 },
  }),
  withReferences({
    id: 'EXPSPACE',
    label: 'EXPSPACE',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Problemas decidibles con espacio exponencial.',
    definition: 'EXPSPACE contiene problemas decidibles usando espacio exponencial. Contiene a EXPTIME/EXP y sigue estando dentro de los lenguajes decidibles porque la cota de espacio finita induce una cota finita de configuraciones alcanzables.',
    intuition: 'Se permite memoria exponencial, pero todavia hay un limite computable.',
    examples: ['problemas con configuraciones exponenciales'],
    commonErrors: ['EXPSPACE esta fuera de lo decidible por ser enorme.'],
    corrections: ['No. EXPSPACE sigue siendo una clase decidible con cota de recurso.'],
    truthStatus: 'definition',
    accent: 'yellow',
    position: { x: 1120, y: -80 },
  }),
  withReferences({
    id: 'Context-sensitive',
    label: 'Context-sensitive',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes generados por gramaticas sensibles al contexto.',
    definition: 'Los lenguajes context-sensitive coinciden con los aceptados por automatas linealmente acotados. Estan por encima de los context-free y siguen siendo decidibles.',
    intuition: 'La memoria lineal permite comparar cantidades y dependencias que un PDA no puede manejar.',
    examples: ['a^n b^n c^n'],
    commonErrors: ['Context-sensitive significa indecidible por ser mas expresivo.'],
    corrections: ['No. Los lenguajes context-sensitive son decidibles.'],
    truthStatus: 'definition',
    accent: 'yellow',
    position: { x: -40, y: -480 },
  }),
  withReferences({
    id: 'LBA',
    label: 'LBA',
    kind: 'algorithm',
    layer: 'advanced',
    shortDefinition: 'Linear Bounded Automaton.',
    definition: 'Un LBA es una maquina de Turing restringida a usar espacio lineal respecto de la entrada. Caracteriza los lenguajes context-sensitive.',
    intuition: 'Es una maquina de Turing con cinta acotada linealmente.',
    examples: ['reconocimiento de a^n b^n c^n'],
    commonErrors: ['Un LBA tiene memoria ilimitada como una TM completa.'],
    corrections: ['No. Su cinta esta acotada linealmente por el tamaño de entrada.'],
    truthStatus: 'definition',
    accent: 'cyan',
    position: { x: -250, y: -520 },
  }),
  withReferences({
    id: 'Context-free',
    label: 'Context-free',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes generados por gramaticas libres de contexto.',
    definition: 'Los lenguajes context-free son generados por gramaticas libres de contexto y reconocidos por automatas con pila. Incluyen patrones anidados como palindromos y balanceo de parentesis.',
    intuition: 'Una pila permite recordar estructura anidada, pero no multiples conteos independientes.',
    examples: ['ww^R', 'parentesis balanceados'],
    commonErrors: ['Todo lenguaje con estructura repetida es context-free.'],
    corrections: ['No. a^n b^n c^n requiere mas poder que una sola pila.'],
    truthStatus: 'definition',
    accent: 'green',
    position: { x: -280, y: -660 },
  }),
  withReferences({
    id: 'Deterministic Context-Free',
    label: 'Deterministic Context-Free',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Subclase determinista de los lenguajes context-free.',
    definition: 'Los lenguajes deterministas libres de contexto son reconocidos por pushdown automata deterministas. Forman una subclase estricta de los context-free generales.',
    intuition: 'La pila existe, pero no hay libertad no determinista para elegir transiciones.',
    examples: ['a^n b^n'],
    commonErrors: ['Todo context-free puede hacerse determinista sin perder lenguaje.'],
    corrections: ['No. Hay lenguajes context-free inherentemente no deterministas.'],
    truthStatus: 'definition',
    accent: 'cyan',
    position: { x: -520, y: -660 },
  }),
  withReferences({
    id: 'Regular',
    label: 'Regular',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes reconocibles por automatas finitos.',
    definition: 'Los lenguajes regulares son reconocidos por automatas finitos y descritos por expresiones regulares formales. No tienen memoria no acotada.',
    intuition: 'Solo hay estado finito; no se puede contar arbitrariamente salvo modulo patrones finitos.',
    examples: ['a*'],
    commonErrors: ['Regex de software y lenguaje regular formal son siempre lo mismo.'],
    corrections: ['No. Muchas regex practicas incluyen extensiones mas poderosas que los regulares formales.'],
    truthStatus: 'definition',
    accent: 'purple',
    position: { x: -760, y: -660 },
  }),
  withReferences({
    id: 'Finite languages',
    label: 'Finite languages',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Lenguajes con cantidad finita de cadenas.',
    definition: 'Los lenguajes finitos contienen solo un numero finito de strings. Todo lenguaje finito es regular porque un automata finito puede reconocer exactamente una lista finita de palabras.',
    intuition: 'Se puede memorizar una lista finita dentro de un automata suficientemente grande.',
    examples: ['{a,b}'],
    commonErrors: ['Un lenguaje finito pequeño no necesita modelo formal.'],
    corrections: ['Sigue siendo un lenguaje formal y pertenece a Regular.'],
    truthStatus: 'definition',
    accent: 'green',
    position: { x: -980, y: -660 },
  }),
  withReferences({
    id: 'Presburger arithmetic',
    label: 'Presburger arithmetic',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'Aritmetica de primer orden con suma, decidible.',
    definition: 'La aritmetica de Presburger es la teoria de primer orden de los naturales con suma pero sin multiplicacion general. Es decidible, aunque con alta complejidad en procedimientos generales.',
    intuition: 'Quitar multiplicacion cambia drasticamente la frontera de decidibilidad.',
    examples: ['formulas con + y cuantificadores'],
    commonErrors: ['Toda aritmetica de primer orden es indecidible.'],
    corrections: ['No. Presburger arithmetic es decidible; Peano arithmetic completa no lo es.'],
    truthStatus: 'theorem',
    accent: 'cyan',
    position: { x: -20, y: 120 },
  }),
  withReferences({
    id: 'RE-complete',
    label: 'RE-complete',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Problemas completos para RE bajo reducciones computables apropiadas.',
    definition: 'Un problema RE-complete pertenece a RE y captura la maxima dificultad de los problemas reconocibles bajo reducciones estandar. Halting Problem es el ejemplo canonico.',
    intuition: 'Es la version de completitud para reconocibilidad, no para tiempo polinomial.',
    examples: ['Halting Problem'],
    commonErrors: ['RE-complete significa NP-complete con otro nombre.'],
    corrections: ['No. RE-complete vive en computabilidad/decidibilidad, no en tiempo polinomial.'],
    truthStatus: 'definition',
    accent: 'red',
    position: { x: -680, y: 20 },
  }),
  withReferences({
    id: 'EXPTIME-complete',
    label: 'EXPTIME-complete',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Problemas completos para EXPTIME/EXP.',
    definition: 'EXPTIME-complete agrupa problemas en EXPTIME tan dificiles como cualquier problema de EXPTIME bajo reducciones polinomiales. Juegos generalizados como Go en tableros adecuados se usan como ejemplos clasicos.',
    intuition: 'Es completitud para tiempo exponencial determinista.',
    examples: ['Go'],
    commonErrors: ['EXPTIME-complete es lo mismo que NP-complete.'],
    corrections: ['No. EXPTIME-complete se ubica en una clase de tiempo mayor que NP bajo inclusiones conocidas.'],
    truthStatus: 'definition',
    accent: 'yellow',
    position: { x: 1120, y: 100 },
  }),
  withReferences({
    id: 'PSPACE-complete',
    label: 'PSPACE-complete',
    kind: 'class',
    layer: 'advanced',
    shortDefinition: 'Problemas completos para PSPACE.',
    definition: 'PSPACE-complete contiene problemas en PSPACE a los que todo problema de PSPACE se reduce en tiempo polinomial. QBF es el problema canonico.',
    intuition: 'Captura la maxima dificultad conocida dentro de espacio polinomial.',
    examples: ['QBF'],
    commonErrors: ['PSPACE-complete implica EXPTIME-complete.'],
    corrections: ['No automaticamente. Son nociones de completitud para clases distintas.'],
    truthStatus: 'definition',
    accent: 'purple',
    position: { x: 900, y: 260 },
  }),
  withReferences({
    id: 'Go',
    label: 'Go',
    kind: 'problem',
    layer: 'problem',
    shortDefinition: 'Juego usado como ejemplo clasico de EXPTIME-completitud en versiones generalizadas.',
    definition: 'Versiones generalizadas de Go se estudian como problemas de decision sobre juegos y son ejemplos clasicos de EXPTIME-completitud bajo formulaciones apropiadas. El punto teorico es el analisis de juegos con arboles de juego exponenciales.',
    intuition: 'El tablero generalizado induce una exploracion estrategica de gran profundidad.',
    examples: ['EXPTIME-complete → Go'],
    commonErrors: ['El Go jugado en tablero fijo prueba completitud EXPTIME por si mismo.'],
    corrections: ['La afirmacion teorica se formula para versiones generalizadas del problema.'],
    truthStatus: 'theorem',
    accent: 'yellow',
    position: { x: 1320, y: 220 },
  }),
];

export const defaultComplexityConceptId: ComplexityConceptId = 'NP';

export function getComplexityConcept(id: string) {
  return complexityConcepts.find((concept) => concept.id === id) ?? complexityConcepts[0];
}
